### ISSUE TITLE
Instructions to download latest snapshot for testnet 5 are not working

### ISSUE THREAD

**Issue by bitcartel** [osmosis-labs/testnets#3]
#### System information

Osmosis version: 15.1.0-testnet
OS & Version: Linux

#### Expected behaviour

Download latest testnet 5 snapshot

#### Actual behaviour

Follow step 4 from here: https://github.com/osmosis-labs/testnets/tree/main/testnets/osmo-test-5

```
SNAPSHOT_URL=$(curl -sL https://snapshots.testnet.osmosis.zone/latest)
wget -q -O - $SNAPSHOT_URL | lz4 -d | tar -C $HOME/.osmosisd/ -xvf -
```

Downloading fails.

```
wget: invalid option -- 'C'
wget: invalid option -- 'f'
wget: invalid option -- '"'
wget: invalid option -- '>'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

```

SNAPSHOT URL is invalid:

```
echo $SNAPSHOT_URL 
<!DOCTYPE html> <html> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <meta http-equiv="X-UA-Compatible" content="ie=edge"> <title>Osmosis Snapshots</title> <meta property="og:type" content="website"> <meta property="og:title" content="Osmosis Snapshots"> <meta property="og:description" content="List of snapshots and 
...
...
```

**Comment by niccoloraspa** [comment]
Thanks. We recently changed the DNS names and there is a problem with the redirect. 
We will fix this.

In the meantime could you please use: https://snapshots.osmotest5.osmosis.zone/latest

**Comment by niccoloraspa** [comment]
<https://snapshots.testnet.osmosis.zone/latest> should also work now.

Thanks for flagging this. Closing the issue.
