### ISSUE TITLE
RPC error to endpoint https://rpc.testnet.osmosis.zone/: HTTP request failed with non-200 status code: 429 Too Many Requests

### ISSUE THREAD

**Issue by mightywomble** [osmosis-labs/testnets#6]
When i run the command hermes query channels --chain osmo-test-5 --show-counterparty
I get this back

ERROR RPC error to endpoint https://rpc.testnet.osmosis.zone/: HTTP request failed with non-200 status code: 429 Too Many Requests

Any way to resolve this on  https://rpc.testnet.osmosis.zone?

**Comment by pablin-10** [comment]
Hello!
This behavior is expected, since our current RPC endpoints for testnet  are rate-limited. 
If you want to rise relayer for testnet its strongly suggested to deploy your own nodes.

Regards!

**Comment by mightywomble** [comment]
Any chance someone could put this information on the README for this repo? Would have saved me a day of work. Thank you.
